## Project Description

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Instalations,-Imports,-Utils-and-Loading-data" data-toc-modified-id="Instalations,-Imports,-Utils-and-Loading-data-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Instalations, Imports, Utils and Loading data</a></span><ul class="toc-item"><li><span><a href="#Instalations" data-toc-modified-id="Instalations-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Instalations</a></span></li><li><span><a href="#Imports" data-toc-modified-id="Imports-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Imports</a></span></li><li><span><a href="#Utils" data-toc-modified-id="Utils-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Utils</a></span></li><li><span><a href="#Loading-Data" data-toc-modified-id="Loading-Data-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Loading Data</a></span></li></ul></li><li><span><a href="#EDA" data-toc-modified-id="EDA-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>EDA</a></span><ul class="toc-item"><li><span><a href="#Looking-at-DataFrames-Data" data-toc-modified-id="Looking-at-DataFrames-Data-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Looking at DataFrames Data</a></span></li><li><span><a href="#Info" data-toc-modified-id="Info-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Info</a></span></li><li><span><a href="#Value-Counts" data-toc-modified-id="Value-Counts-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Value Counts</a></span></li><li><span><a href="#Duplicates" data-toc-modified-id="Duplicates-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Duplicates</a></span></li><li><span><a href="#Missing-Values" data-toc-modified-id="Missing-Values-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>Missing Values</a></span></li><li><span><a href="#Merging-DataFrames" data-toc-modified-id="Merging-DataFrames-2.6"><span class="toc-item-num">2.6&nbsp;&nbsp;</span>Merging DataFrames</a></span></li><li><span><a href="#Handeling-Missing-values-from-merge" data-toc-modified-id="Handeling-Missing-values-from-merge-2.7"><span class="toc-item-num">2.7&nbsp;&nbsp;</span>Handeling Missing values from merge</a></span></li><li><span><a href="#Handeling-missing-values-and-types" data-toc-modified-id="Handeling-missing-values-and-types-2.8"><span class="toc-item-num">2.8&nbsp;&nbsp;</span>Handeling missing values and types</a></span><ul class="toc-item"><li><span><a href="#Create-is_customer" data-toc-modified-id="Create-is_customer-2.8.1"><span class="toc-item-num">2.8.1&nbsp;&nbsp;</span>Create is_customer</a></span></li><li><span><a href="#begin_date-and-end_date" data-toc-modified-id="begin_date-and-end_date-2.8.2"><span class="toc-item-num">2.8.2&nbsp;&nbsp;</span>begin_date and end_date</a></span></li><li><span><a href="#type-column" data-toc-modified-id="type-column-2.8.3"><span class="toc-item-num">2.8.3&nbsp;&nbsp;</span>type column</a></span></li><li><span><a href="#total_charges" data-toc-modified-id="total_charges-2.8.4"><span class="toc-item-num">2.8.4&nbsp;&nbsp;</span>total_charges</a></span></li></ul></li><li><span><a href="#Feature-Engineering" data-toc-modified-id="Feature-Engineering-2.9"><span class="toc-item-num">2.9&nbsp;&nbsp;</span>Feature Engineering</a></span><ul class="toc-item"><li><span><a href="#Creating-month_duration" data-toc-modified-id="Creating-month_duration-2.9.1"><span class="toc-item-num">2.9.1&nbsp;&nbsp;</span>Creating month_duration</a></span></li><li><span><a href="#Spliting-begin_date-to-year-and-month-columns-Dropping-date-columns" data-toc-modified-id="Spliting-begin_date-to-year-and-month-columns-Dropping-date-columns-2.9.2"><span class="toc-item-num">2.9.2&nbsp;&nbsp;</span><del>Spliting begin_date to year and month columns</del> Dropping date columns</a></span></li><li><span><a href="#Downcasting-int-columns" data-toc-modified-id="Downcasting-int-columns-2.9.3"><span class="toc-item-num">2.9.3&nbsp;&nbsp;</span>Downcasting int columns</a></span></li></ul></li></ul></li><li><span><a href="#Data-Analysis" data-toc-modified-id="Data-Analysis-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Data Analysis</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Class-Balance" data-toc-modified-id="Class-Balance-3.0.1"><span class="toc-item-num">3.0.1&nbsp;&nbsp;</span>Class Balance</a></span></li><li><span><a href="#Correlation" data-toc-modified-id="Correlation-3.0.2"><span class="toc-item-num">3.0.2&nbsp;&nbsp;</span>Correlation</a></span></li></ul></li></ul></li><li><span><a href="#Preparing-For-Model-Training" data-toc-modified-id="Preparing-For-Model-Training-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Preparing For Model Training</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#DummyClassifier" data-toc-modified-id="DummyClassifier-4.0.1"><span class="toc-item-num">4.0.1&nbsp;&nbsp;</span>DummyClassifier</a></span></li><li><span><a href="#LogisticRegression" data-toc-modified-id="LogisticRegression-4.0.2"><span class="toc-item-num">4.0.2&nbsp;&nbsp;</span>LogisticRegression</a></span></li><li><span><a href="#Random-Forest" data-toc-modified-id="Random-Forest-4.0.3"><span class="toc-item-num">4.0.3&nbsp;&nbsp;</span>Random Forest</a></span></li><li><span><a href="#CatBoost" data-toc-modified-id="CatBoost-4.0.4"><span class="toc-item-num">4.0.4&nbsp;&nbsp;</span>CatBoost</a></span><ul class="toc-item"><li><span><a href="#SMOTE" data-toc-modified-id="SMOTE-4.0.4.1"><span class="toc-item-num">4.0.4.1&nbsp;&nbsp;</span>SMOTE</a></span></li></ul></li></ul></li></ul></li><li><span><a href="#Conclusions" data-toc-modified-id="Conclusions-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Conclusions</a></span></li></ul></div>

## Installations, Imports, Utils and Loading data

### Imports

In [2]:
# Importing pandas libarary.
import pandas as pd

# Importing NumPy library.
import numpy as np

# Importing Visualizations
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import ConfusionMatrixDisplay

# Best parameter search 
from sklearn.model_selection import GridSearchCV

# utils:
from sklearn.preprocessing import MinMaxScaler, StandardScaler, OrdinalEncoder,OneHotEncoder       
from sklearn.model_selection import train_test_split                 
import re                                            
from time import perf_counter as timer               
from IPython.display import display_html

### Utils

In [11]:
def convert(name):
    '''Converting column names to lower case'''
    pattern = re.compile(r"[A-Z]{2,}(?=[A-Z][a-z]+[0-9]*|\b)|[A-Z]?[a-z]+[0-9]*|[A-Z]|[0-9]+")
    found = pattern.findall(name)
    s1 = "_".join(found)
    return s1.lower()

In [12]:
def side_by_side_display(df_ls, captions=[], title=''):
    df_ls = [df if type(df) == pd.DataFrame else pd.DataFrame(df) for df in df_ls]
    df_to_display = ''
    for i in range(len(df_ls)):
        if 0 <= i < len(captions):
            caption = captions[i]
        else:
            caption = ''
        df_style = df_ls[i].style.set_table_attributes("style='display:inline'").set_caption(caption)
        df_to_display += df_style._repr_html_()
    print(title)
    display_html(df_to_display, raw=True)

In [13]:
from IPython.display import display
pd.options.display.max_rows = 100

In [14]:
import sys
import warnings
if not sys.warnoptions:
    warnings.simplefilter("ignore")

In [15]:
# Converting the default of pandas to show regular numbers instead of Scientific Notation.
pd.set_option('display.float_format', lambda x: '%.3f' % x)

### Loading Data

In [16]:
# Loading data
train = pd.read_csv('./train.csv')
test = pd.read_csv('./test.csv')

In [17]:
# Changes the columns names to lower case and separate the words using _ e.g:
# BoldMove => bold_move.
for df in [train, test]:
    new_columns = [convert(col) for col in df.columns.to_list()]
    df.columns = new_columns

In [18]:
train

,id,ms_sub_class,ms_zoning,lot_frontage,lot_area,street,alley,lot_shape,land_contour,utilities,...,pool_area,pool_qc,fence,misc_feature,misc_val,mo_sold,yr_sold,sale_type,sale_condition,sale_price
0,1,60,RL,65.000,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.000,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.000,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.000,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.000,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.000,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.000,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.000,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.000,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.000,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

Some observations

### EDA

In [19]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1460 non-null   int64
 1   ms_sub_class     1460 non-null   int64
 2   ms_zoning        1460 non-null   object
 3   lot_frontage     1201 non-null   float64
 4   lot_area         1460 non-null   int64
 5   street           1460 non-null   object
 6   alley            91 non-null     object
 7   lot_shape        1460 non-null   object
 8   land_contour     1460 non-null   object
 9   utilities        1460 non-null   object
 10  lot_config       1460 non-null   object
 11  land_slope       1460 non-null   object
 12  neighborhood     1460 non-null   object
 13  condition1       1460 non-null   object
 14  condition2       1460 non-null   object
 15  bldg_type        1460 non-null   object
 16  house_style      1460 non-null   object
 17  overall_qual     1460 non-null   int64
 18  overall_cond     1460 non-null   int64
 19  year_built       1460 non-null   int64
 20  year_remod_add   1460 non-null   int64
 21  roof_style       1460 non-null   object
 22  roof_matl        1460 non-null   object
 23  exterior1_st     1460 non-null   object
 24  exterior2_nd     1460 non-null   object
 25  mas_vnr_type     1452 non-null   object
 26  mas_vnr_area     1452 non-null   float64
 27  exter_qual       1460 non-null   object
 28  exter_cond       1460 non-null   object
 29  foundation       1460 non-null   object
 30  bsmt_qual        1423 non-null   object
 31  bsmt_cond        1423 non-null   object
 32  bsmt_exposure    1422 non-null   object
 33  bsmt_fin_type1   1423 non-null   object
 34  bsmt_fin_s_f_1   1460 non-null   int64
 35  bsmt_fin_type2   1422 non-null   object
 36  bsmt_fin_s_f_2   1460 non-null   int64
 37  bsmt_unf_sf      1460 non-null   int64
 38  total_bsmt_sf    1460 non-null   int64
 39  heating          1460 non-null   object
 40  heating_qc       1460 non-null   object
 41  central_air      1460 non-null   object
 42  electrical       1459 non-null   object
 43  1_st_flr_sf      1460 non-null   int64
 44  2_nd_flr_sf      1460 non-null   int64
 45  low_qual_fin_sf  1460 non-null   int64
 46  gr_liv_area      1460 non-null   int64
 47  bsmt_full_bath   1460 non-null   int64
 48  bsmt_half_bath   1460 non-null   int64
 49  full_bath        1460 non-null   int64
 50  half_bath        1460 non-null   int64
 51  bedroom_abv_gr   1460 non-null   int64
 52  kitchen_abv_gr   1460 non-null   int64
 53  kitchen_qual     1460 non-null   object
 54  tot_rms_abv_grd  1460 non-null   int64
 55  functional       1460 non-null   object
 56  fireplaces       1460 non-null   int64
 57  fireplace_qu     770 non-null    object
 58  garage_type      1379 non-null   object
 59  garage_yr_blt    1379 non-null   float64
 60  garage_finish    1379 non-null   object
 61  garage_cars      1460 non-null   int64
 62  garage_area      1460 non-null   int64
 63  garage_qual      1379 non-null   object
 64  garage_cond      1379 non-null   object
 65  paved_drive      1460 non-null   object
 66  wood_deck_sf     1460 non-null   int64
 67  open_porch_sf    1460 non-null   int64
 68  enclosed_porch   1460 non-null   int64
 69  3_ssn_porch      1460 non-null   int64
 70  screen_porch     1460 non-null   int64
 71  pool_area        1460 non-null   int64
 72  pool_qc          7 non-null      object
 73  fence            281 non-null    object
 74  misc_feature     54 non-null     object
 75  misc_val         1460 non-null   int64
 76  mo_sold          1460 non-null   int64
 77  yr_sold          1460 non-null   int64
 78  sale_type        1460 non-null   object
 79  sale_condition   1460 non-null   object
 80  sale_price       1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

Observations:

### Checking for duplicate, NA, strange values

In [20]:
train.duplicated().sum()

0

In [25]:
train_is_na = train.isna().sum() 
train_is_na[train_is_na > 0]

lot_frontage       259
alley             1369
mas_vnr_type         8
mas_vnr_area         8
bsmt_qual           37
bsmt_cond           37
bsmt_exposure       38
bsmt_fin_type1      37
bsmt_fin_type2      38
electrical           1
fireplace_qu       690
garage_type         81
garage_yr_blt       81
garage_finish       81
garage_qual         81
garage_cond         81
pool_qc           1453
fence             1179
misc_feature      1406
dtype: int64

### Feature Engineering